blank_issues_enabled: false
contact_links:
  - name: Questions
    url: "https://github.com/stickz/rTorrent-seedbox/discussions/categories/q-a"
    about: "Please ask questions related to rTorrent seedbox in the Discussions section"
