name: rTorrent Pull Request

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  amd:
    runs-on: [self-hosted, linux, x86, amd]
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Build AMD Debian 12 x86
        run: ./.github/scripts/build.sh
        shell: bash
  arm:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Build ARM64 Debian 12
        run: ./.github/scripts/build.sh
        shell: bash
