name: rTorrent Push Commit

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  arm:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Build ARM64 Debian 12
        run: ./.github/scripts/build.sh
        shell: bash
